# Generated by Django 4.0.4 on 2022-04-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradePotentialAnalyser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.IntegerField()),
                ('Trade_Partner', models.CharField(default='', max_length=255)),
                ('Trading_Out_Num', models.IntegerField()),
                ('Trading_Out_Num_Player', models.IntegerField()),
                ('Trading_In_Num', models.IntegerField()),
                ('Trading_In_Num_Player', models.IntegerField()),
                ('note', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trade_Partner', models.CharField(default='', max_length=255)),
                ('Trading_Out', models.CharField(default='', max_length=255)),
                ('Trading_In', models.CharField(default='', max_length=255)),
                ('Points_Out', models.CharField(default='', max_length=255)),
                ('Points_In', models.CharField(default='', max_length=255)),
                ('Points_Diff', models.CharField(default='', max_length=255)),
                ('Notes', models.CharField(default='', max_length=255)),
                ('System_Out', models.CharField(default='', max_length=255)),
                ('System_In', models.CharField(default='', max_length=255)),
                ('Warning', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
