# Generated by Django 3.1.7 on 2022-03-28 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterlist',
            old_name='project_Id',
            new_name='projectid',
        ),
    ]
