# Generated by Django 3.1.8 on 2022-03-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterlist',
            name='Unique_Pick_ID',
            field=models.CharField(default='', max_length=100),
        ),
    ]
