# Generated by Django 4.0.4 on 2022-05-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterlist',
            name='Selected_Player',
            field=models.CharField(default='', max_length=100),
        ),
    ]
