# Generated by Django 3.1.7 on 2022-04-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trade_Partner', models.CharField(default='', max_length=255)),
                ('Trading_Out', models.CharField(default='', max_length=255)),
                ('Trading_In', models.CharField(default='', max_length=255)),
                ('Points_Out', models.CharField(default='', max_length=255)),
                ('Points_In', models.CharField(default='', max_length=255)),
                ('Points_Diff', models.CharField(default='', max_length=255)),
                ('Notes', models.CharField(default='', max_length=255)),
                ('System_Out', models.CharField(default='', max_length=255)),
                ('System_In', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
