# Generated by Django 3.1.7 on 2022-04-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterlist',
            name='Display_Name_Mini',
            field=models.TextField(),
        ),
    ]
