# Generated by Django 3.1.8 on 2022-02-21 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addteam',
            name='project_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='RestApp.project'),
        ),
        migrations.AddField(
            model_name='localladder',
            name='Project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='RestApp.project'),
        ),
        migrations.AddField(
            model_name='masterlist',
            name='project_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='RestApp.project'),
        ),
    ]
