# Generated by Django 3.1.8 on 2022-02-23 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterlist',
            name='ShortName',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='masterlist_requests_created', to='RestApp.teams'),
        ),
    ]
