# Generated by Django 3.1.7 on 2022-03-14 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtrade',
            old_name='Team1_Pick1',
            new_name='Team1_Pick1_no',
        ),
        migrations.RenameField(
            model_name='addtrade',
            old_name='Team1_Pick2',
            new_name='Team1_player_no',
        ),
        migrations.RenameField(
            model_name='addtrade',
            old_name='Team2_Pick1',
            new_name='Team2_Pick1_no',
        ),
        migrations.RenameField(
            model_name='addtrade',
            old_name='Team2_Pick2',
            new_name='Team2_player_no',
        ),
        migrations.RemoveField(
            model_name='addtrade',
            name='Team1_Pick3',
        ),
        migrations.RemoveField(
            model_name='addtrade',
            name='Team2_Pick3',
        ),
        migrations.AddField(
            model_name='addtrade',
            name='projectid',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
