# Generated by Django 3.1.7 on 2022-03-25 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prioritypick',
            old_name='projectid',
            new_name='projectId',
        ),
    ]
