# Generated by Django 3.1.8 on 2022-02-22 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localladder',
            old_name='projectId',
            new_name='project',
        ),
    ]
