# Generated by Django 3.1.7 on 2022-03-07 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddTrade',
        ),
    ]
