# Generated by Django 3.1.7 on 2022-03-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterlist',
            name='Current_Owner_Short_Name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='masterlist',
            name='Display_Name_Mini',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='masterlist',
            name='Display_Name_Short',
            field=models.CharField(default='', max_length=100),
        ),
    ]
