# Generated by Django 3.1.8 on 2022-02-14 19:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uui',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=10, unique=True),
        ),
    ]
