# Generated by Django 3.1.7 on 2022-02-08 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterlist',
            name='Most_Recent_Owner',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='Most_Recent_Owner', to='RestApp.addteam'),
        ),
    ]
