# Generated by Django 3.1.8 on 2022-02-16 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addteam',
            old_name='ShorName',
            new_name='ShortName',
        ),
    ]
