# Generated by Django 4.0.4 on 2022-05-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0002_tradepotentialanalyser_trades'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='projectId',
            field=models.IntegerField(null=True),
        ),
    ]
