# Generated by Django 4.0.4 on 2022-05-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0002_alter_masterlist_selected_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update_ladder_teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeamNames', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
