# Generated by Django 3.1.7 on 2022-03-16 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0002_auto_20220315_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityPick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='', max_length=250)),
                ('pp_insert_instructions', models.CharField(default='', max_length=250)),
                ('Team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RestApp.teams')),
            ],
        ),
    ]
