# Generated by Django 3.1.8 on 2022-02-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0002_auto_20220221_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Active',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='', max_length=1),
        ),
    ]
