# Generated by Django 3.1.8 on 2022-03-08 17:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0002_auto_20220308_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Transaction_DateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 17, 3, 25, 750298, tzinfo=utc)),
        ),
    ]
