# Generated by Django 3.1.7 on 2022-03-25 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0002_auto_20220326_0516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prioritypick',
            old_name='projectId',
            new_name='projectid',
        ),
    ]
