# Generated by Django 3.1.7 on 2022-04-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0002_auto_20220408_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterlist',
            name='Draft_Round_Int',
            field=models.CharField(default='', max_length=100),
        ),
    ]
