# Generated by Django 3.1.7 on 2022-02-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0002_masterlist_most_recent_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localladder',
            name='season',
            field=models.CharField(default='', max_length=100),
        ),
    ]
