# Generated by Django 3.1.7 on 2022-04-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0002_trades'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='Warning',
            field=models.CharField(default='', max_length=255),
        ),
    ]
