# Generated by Django 3.1.7 on 2022-03-14 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0002_auto_20220315_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTradeV2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.IntegerField()),
                ('Team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestApp.teams')),
                ('Team1_Pick1_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addtradev2_requests_created', to='RestApp.masterlist')),
                ('Team1_player_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team1_Pick1', to='RestApp.masterlist')),
                ('Team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addtradev2_requests_created', to='RestApp.teams')),
                ('Team2_Pick1_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team1_Pick3', to='RestApp.masterlist')),
                ('Team2_player_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team2_Pick1', to='RestApp.masterlist')),
            ],
        ),
        migrations.DeleteModel(
            name='AddTrade',
        ),
    ]
