# Generated by Django 3.1.7 on 2022-04-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0002_auto_20220401_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='Image',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
