# Generated by Django 3.1.8 on 2022-02-17 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0002_auto_20220217_0334'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AcademyTeam', models.CharField(default='', max_length=100)),
                ('AcademyPickType', models.CharField(default='', max_length=100)),
                ('AcademyBid', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ManualTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ManualTeam', models.CharField(default='', max_length=100)),
                ('ManualRound', models.CharField(default='', max_length=100)),
                ('ManualAlignedPick', models.CharField(default='', max_length=100)),
                ('ManualInstructions', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PriorityPick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PriorityPickType', models.CharField(max_length=100)),
                ('PriorityAlignedPick', models.CharField(default='', max_length=100)),
                ('PriorityPickInstaructions', models.CharField(default='', max_length=100)),
                ('PriorityTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestApp.addteam')),
            ],
        ),
        migrations.CreateModel(
            name='FA_Compansations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fa_PickType', models.CharField(default='', max_length=100)),
                ('Fa_Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestApp.addteam')),
            ],
        ),
        migrations.CreateModel(
            name='AddTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team1_Pick1', models.CharField(default='', max_length=100)),
                ('Team1_Pick2', models.CharField(default='', max_length=100)),
                ('Team1_Pick3', models.CharField(default='', max_length=100)),
                ('Team2_Pick1', models.CharField(default='', max_length=100)),
                ('Team2_Pick2', models.CharField(default='', max_length=100)),
                ('Team2_Pick3', models.CharField(default='', max_length=100)),
                ('Team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestApp.addteam')),
                ('Team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addtrade_requests_created', to='RestApp.addteam')),
            ],
        ),
    ]
