# Generated by Django 3.1.8 on 2022-02-23 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0002_auto_20220224_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterlist',
            name='ShortName',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='masterlist_requests_created', to='RestApp.teams'),
        ),
    ]
