# Generated by Django 3.1.8 on 2022-03-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0002_auto_20220303_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='library_AFL_Draft_Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
