# Generated by Django 4.0.4 on 2022-05-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0003_players_projectid'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='projectid',
            field=models.IntegerField(null=True),
        ),
    ]
