# Generated by Django 4.0.4 on 2022-05-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0003_update_ladder_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update_ladder_teams',
            old_name='TeamNames',
            new_name='updated_ladderlist_current_year',
        ),
        migrations.AddField(
            model_name='update_ladder_teams',
            name='updated_ladderlist_current_year_plus1',
            field=models.CharField(default='', max_length=255),
        ),
    ]
