# Generated by Django 3.1.8 on 2022-02-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0003_auto_20220224_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterlist',
            name='Year',
            field=models.CharField(default='', max_length=100),
        ),
    ]
