# Generated by Django 3.1.8 on 2022-02-18 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0003_academybid_addtrade_fa_compansations_manualteam_prioritypick'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prioritypick',
            old_name='PriorityPickInstaructions',
            new_name='PriorityPickInstructions',
        ),
    ]
