# Generated by Django 3.1.7 on 2022-03-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0003_prioritypick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtradev2',
            name='Team1_player_no',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='addtradev2',
            name='Team2_player_no',
            field=models.CharField(default='', max_length=250),
        ),
    ]
