# Generated by Django 3.1.8 on 2022-03-04 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0003_library_afl_draft_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtrade',
            name='Team1_Pick1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addtrade_requests_created', to='RestApp.masterlist'),
        ),
        migrations.AlterField(
            model_name='addtrade',
            name='Team1_Pick2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team1_Pick1', to='RestApp.masterlist'),
        ),
        migrations.AlterField(
            model_name='addtrade',
            name='Team1_Pick3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team1_Pick2', to='RestApp.masterlist'),
        ),
        migrations.AlterField(
            model_name='addtrade',
            name='Team2_Pick1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team1_Pick3', to='RestApp.masterlist'),
        ),
        migrations.AlterField(
            model_name='addtrade',
            name='Team2_Pick2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team2_Pick1', to='RestApp.masterlist'),
        ),
        migrations.AlterField(
            model_name='addtrade',
            name='Team2_Pick3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team2_Pick2', to='RestApp.masterlist'),
        ),
    ]
