# Generated by Django 3.1.7 on 2022-04-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0003_masterlist_draft_round_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterlist',
            name='Draft_Round_Int',
            field=models.TextField(),
        ),
    ]
