# Generated by Django 4.0.4 on 2022-05-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0003_auto_20220516_1707'),
        ('RestApp', '0004_trades_projectid'),
    ]

    operations = [
    ]
