# Generated by Django 3.1.7 on 2022-05-17 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0003_auto_20220516_1707'),
        ('RestApp', '0004_trades_projectid'),
    ]

    operations = [
    ]
