# Generated by Django 3.1.7 on 2022-04-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0004_auto_20220414_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterlist',
            name='Pick_Status',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='masterlist',
            name='Reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='masterlist',
            name='Selected_Player',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='masterlist',
            name='System_Note',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='masterlist',
            name='User_Note',
            field=models.TextField(),
        ),
    ]
