# Generated by Django 3.1.8 on 2022-02-21 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0004_remove_addteam_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryAFLTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdelaideCrows', models.CharField(default='', max_length=100)),
                ('BrisbaneLions', models.CharField(default='', max_length=100)),
                ('Carlton', models.CharField(default='', max_length=100)),
                ('Collingwood', models.CharField(default='', max_length=100)),
                ('Essendon', models.CharField(default='', max_length=100)),
                ('Fremantle', models.CharField(default='', max_length=100)),
                ('GeelongCats', models.CharField(default='', max_length=100)),
                ('GoldCoastSuns', models.CharField(default='', max_length=100)),
                ('GWSGiants', models.CharField(default='', max_length=100)),
                ('Hawthorn', models.CharField(default='', max_length=100)),
                ('Melbourne', models.CharField(default='', max_length=100)),
                ('NorthMelbourne', models.CharField(default='', max_length=100)),
                ('PortAdelaide', models.CharField(default='', max_length=100)),
                ('Richmond', models.CharField(default='', max_length=100)),
                ('StKilda', models.CharField(default='', max_length=100)),
                ('SydneySwans', models.CharField(default='', max_length=100)),
                ('WestCoastEagles', models.CharField(default='', max_length=100)),
                ('WesternBulldogs', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PicksType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartOfDraft', models.CharField(default='', max_length=100)),
                ('FirstRound', models.CharField(default='', max_length=100)),
                ('FirstRoundEnd', models.CharField(default='', max_length=100)),
                ('SecondRound', models.CharField(default='', max_length=100)),
                ('SecondRoundEnd', models.CharField(default='', max_length=100)),
                ('CustomFixedPositions', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='academybid',
            name='AcademyPickType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestApp.pickstype'),
        ),
        migrations.AlterField(
            model_name='academybid',
            name='AcademyTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestApp.libraryaflteams'),
        ),
        migrations.AlterField(
            model_name='fa_compansations',
            name='Fa_PickType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestApp.pickstype'),
        ),
        migrations.AlterField(
            model_name='fa_compansations',
            name='Fa_Team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestApp.libraryaflteams'),
        ),
        migrations.AlterField(
            model_name='manualteam',
            name='ManualTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestApp.libraryaflteams'),
        ),
        migrations.AlterField(
            model_name='prioritypick',
            name='PriorityPickType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestApp.pickstype'),
        ),
    ]
