# Generated by Django 3.1.8 on 2022-02-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0004_auto_20220219_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='names',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='players',
            name='notes',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='players',
            name='ratings',
            field=models.CharField(default='', max_length=100),
        ),
    ]
