# Generated by Django 3.1.7 on 2022-03-17 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0004_auto_20220317_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtradev2',
            name='Player_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RestApp.players'),
        ),
    ]
