# Generated by Django 3.1.8 on 2022-02-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0004_auto_20220225_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterlist',
            name='ShortName',
        ),
        migrations.AddField(
            model_name='masterlist',
            name='Position',
            field=models.CharField(default='', max_length=100),
        ),
    ]
