# Generated by Django 3.1.7 on 2022-03-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0004_auto_20220305_0331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterlist',
            name='Unique_Pick_Id',
        ),
        migrations.AlterField(
            model_name='masterlist',
            name='Unique_Pick_ID',
            field=models.CharField(default='', max_length=100),
        ),
    ]
