# Generated by Django 3.1.8 on 2022-03-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0004_auto_20220308_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Transaction_DateTime',
            field=models.CharField(default='', max_length=100),
        ),
    ]
