# Generated by Django 4.0.4 on 2022-05-27 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0004_rename_teamnames_update_ladder_teams_updated_ladderlist_current_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update_ladder_teams',
            old_name='updated_ladderlist_current_year',
            new_name='updated_ladderlist_TeamName',
        ),
        migrations.RemoveField(
            model_name='update_ladder_teams',
            name='updated_ladderlist_current_year_plus1',
        ),
    ]
