# Generated by Django 3.1.7 on 2022-02-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0004_auto_20220128_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalLadder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default='', max_length=100)),
                ('season', models.CharField(max_length=100)),
                ('teamname', models.CharField(max_length=100)),
                ('shortname', models.CharField(max_length=100)),
            ],
        ),
    ]
