# Generated by Django 3.1.8 on 2022-02-21 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0005_auto_20220222_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtrade',
            name='Team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestApp.libraryaflteams'),
        ),
    ]
