# Generated by Django 3.1.8 on 2022-02-24 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0005_auto_20220225_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterlist',
            name='Most_Recent_Owner',
        ),
        migrations.AddField(
            model_name='masterlist',
            name='Previous_Owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Previous_Owner', to='RestApp.teams'),
        ),
        migrations.AlterField(
            model_name='masterlist',
            name='Current_Owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Current_Owner', to='RestApp.teams'),
        ),
    ]
