# Generated by Django 3.1.8 on 2022-03-08 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0005_auto_20220308_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestApp.teams')),
                ('Team1_Pick1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addtrade_requests_created', to='RestApp.masterlist')),
                ('Team1_Pick2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team1_Pick1', to='RestApp.masterlist')),
                ('Team1_Pick3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team1_Pick2', to='RestApp.masterlist')),
                ('Team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addtrade_requests_created', to='RestApp.teams')),
                ('Team2_Pick1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team1_Pick3', to='RestApp.masterlist')),
                ('Team2_Pick2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team2_Pick1', to='RestApp.masterlist')),
                ('Team2_Pick3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team2_Pick2', to='RestApp.masterlist')),
            ],
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
