# Generated by Django 3.1.7 on 2022-03-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0005_addtradev2_player_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtradev2',
            name='Player_Name',
        ),
        migrations.AddField(
            model_name='addtradev2',
            name='Team1_Player_Name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
