# Generated by Django 3.1.7 on 2022-04-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0005_auto_20220406_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='Image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
