# Generated by Django 3.1.7 on 2022-04-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0005_auto_20220414_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterlist',
            name='Pick_Status',
            field=models.TextField(),
        ),
    ]
