# Generated by Django 3.1.7 on 2022-03-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0006_auto_20220324_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtradev2',
            name='Team2_Player_Name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
