# Generated by Django 3.1.7 on 2022-04-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0006_auto_20220414_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterlist',
            name='Selected_Player',
            field=models.TextField(),
        ),
    ]
