# Generated by Django 3.1.7 on 2022-02-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0006_createproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(default='', max_length=100)),
                ('Transaction_Number', models.IntegerField()),
                ('Transaction_DateTime', models.DateField()),
                ('Transaction_Type', models.CharField(default='', max_length=100)),
                ('Transaction_Details', models.CharField(default='', max_length=100)),
                ('Transaction_Description', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
