# Generated by Django 3.1.7 on 2022-04-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0006_auto_20220406_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterlist',
            name='Pick_Status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='masterlist',
            name='Selected_Player',
            field=models.CharField(default='', max_length=100),
        ),
    ]
