# Generated by Django 3.1.8 on 2022-02-21 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0007_auto_20220222_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libraryaflteams',
            old_name='AdelaideCrows',
            new_name='TeamNames',
        ),
        migrations.RemoveField(
            model_name='libraryaflteams',
            name='BrisbaneLions',
        ),
        migrations.RemoveField(
            model_name='libraryaflteams',
            name='Carlton',
        ),
        migrations.RemoveField(
            model_name='libraryaflteams',
            name='Collingwood',
        ),
        migrations.RemoveField(
            model_name='libraryaflteams',
            name='Essendon',
        ),
        migrations.RemoveField(
            model_name='libraryaflteams',
            name='Fremantle',
        ),
        migrations.RemoveField(
            model_name='libraryaflteams',
            name='GWSGiants',
        ),
        migrations.RemoveField(
            model_name='libraryaflteams',
            name='GeelongCats',
        ),
        migrations.RemoveField(
            model_name='libraryaflteams',
            name='GoldCoastSuns',
        ),
        migrations.RemoveField(
            model_name='libraryaflteams',
            name='Hawthorn',
        ),
        migrations.RemoveField(
            model_name='libraryaflteams',
            name='Melbourne',
        ),
        migrations.RemoveField(
            model_name='libraryaflteams',
            name='NorthMelbourne',
        ),
        migrations.RemoveField(
            model_name='libraryaflteams',
            name='PortAdelaide',
        ),
        migrations.RemoveField(
            model_name='libraryaflteams',
            name='Richmond',
        ),
        migrations.RemoveField(
            model_name='libraryaflteams',
            name='StKilda',
        ),
        migrations.RemoveField(
            model_name='libraryaflteams',
            name='SydneySwans',
        ),
        migrations.RemoveField(
            model_name='libraryaflteams',
            name='WestCoastEagles',
        ),
        migrations.RemoveField(
            model_name='libraryaflteams',
            name='WesternBulldogs',
        ),
    ]
