# Generated by Django 3.1.8 on 2022-03-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0007_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Transaction_Description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Transaction_Details',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Transaction_Type',
            field=models.CharField(default='', max_length=500),
        ),
    ]
