# Generated by Django 3.1.7 on 2022-04-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0007_auto_20220414_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='Type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
