# Generated by Django 3.1.7 on 2022-02-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0007_masterlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterlist',
            name='Transaction_DateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
