# Generated by Django 3.1.7 on 2022-03-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0007_addtradev2_team2_player_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
