# Generated by Django 3.1.7 on 2022-02-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0008_auto_20220202_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uui',
            field=models.CharField(default='', max_length=100),
        ),
    ]
