# Generated by Django 3.1.8 on 2022-02-21 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0008_auto_20220222_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtrade',
            name='Team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addtrade_requests_created', to='RestApp.libraryaflteams'),
        ),
        migrations.AlterField(
            model_name='prioritypick',
            name='PriorityTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestApp.libraryaflteams'),
        ),
    ]
