# Generated by Django 3.1.7 on 2022-04-06 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0008_auto_20220406_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Team',
        ),
    ]
