# Generated by Django 3.1.7 on 2022-04-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0008_auto_20220406_2211'),
        ('RestApp', '0008_auto_20220406_2209'),
        ('RestApp', '0008_auto_20220406_2156'),
        ('RestApp', '0008_auto_20220406_2210'),
    ]

    operations = [
    ]
