# Generated by Django 3.1.7 on 2022-04-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0008_transactions_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Type',
            field=models.CharField(default='  ', max_length=100),
        ),
    ]
