# Generated by Django 3.1.8 on 2022-02-16 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0008_auto_20220216_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='localladder',
            name='teamname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestApp.addteam'),
        ),
        migrations.AlterField(
            model_name='masterlist',
            name='Current_Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masterlist_requests_created', to='RestApp.addteam'),
        ),
        migrations.AlterField(
            model_name='masterlist',
            name='Most_Recent_Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Most_Recent_Owner', to='RestApp.addteam'),
        ),
        migrations.AlterField(
            model_name='masterlist',
            name='Original_Owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='RestApp.addteam'),
        ),
        migrations.CreateModel(
            name='DraftAnalyserTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradePartner', models.CharField(default='', max_length=100)),
                ('TotalPicks', models.CharField(default='', max_length=100)),
                ('TotalPLayers', models.CharField(default='', max_length=100)),
                ('PickTradingIn', models.CharField(default='', max_length=100)),
                ('PlayerTradingIn', models.CharField(default='', max_length=100)),
                ('TradeNotes', models.CharField(default='', max_length=250)),
                ('PlayerName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestApp.players')),
            ],
        ),
    ]
