# Generated by Django 3.1.7 on 2022-02-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0009_user_uui'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uui',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
