# Generated by Django 3.1.7 on 2022-04-06 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0009_remove_user_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Team',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='RestApp.teams'),
        ),
    ]
