# Generated by Django 3.1.8 on 2022-02-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0009_auto_20220217_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftanalysertrade',
            name='TradeNotes',
            field=models.TextField(default='', max_length=250),
        ),
    ]
