# Generated by Django 3.1.8 on 2022-02-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0009_auto_20220222_0332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='names',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='players',
            old_name='ratings',
            new_name='Height',
        ),
        migrations.RemoveField(
            model_name='players',
            name='notes',
        ),
        migrations.AddField(
            model_name='players',
            name='LastName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='players',
            name='Notes',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='players',
            name='Position_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='players',
            name='Position_2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='players',
            name='Rank',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='players',
            name='State',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='players',
            name='Tier',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='players',
            name='club',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='players',
            name='width',
            field=models.CharField(default='', max_length=100),
        ),
    ]
