# Generated by Django 3.1.8 on 2022-02-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0010_auto_20220217_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftanalysertrade',
            name='TradeNotes',
            field=models.TextField(default='', max_length=200),
        ),
    ]
