# Generated by Django 3.1.8 on 2022-02-16 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0011_auto_20220217_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='Transaction_Number',
        ),
    ]
