# Generated by Django 4.0.5 on 2022-07-01 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0012_alter_masterlist_previous_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterlist',
            name='Previous_Owner',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Previous_Owner', to='RestApp.teams'),
        ),
    ]
