# Generated by Django 3.1.7 on 2022-02-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0015_auto_20220205_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=100)),
                ('Contact', models.CharField(default='', max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('ActiveOrInactive', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
