# Generated by Django 3.1.7 on 2022-02-07 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0016_makecompany'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MakeUser',
        ),
    ]
