# Generated by Django 3.1.7 on 2022-02-07 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0017_auto_20220208_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makecompany',
            name='ActiveOrInactive',
        ),
    ]
