# Generated by Django 3.1.7 on 2022-02-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0018_remove_makecompany_activeorinactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeamName', models.CharField(max_length=100)),
                ('ShortName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction_Number', models.IntegerField()),
                ('Transaction_DateTime', models.DateTimeField(auto_now_add=True)),
                ('Transaction_Type', models.CharField(default='', max_length=100)),
                ('Transaction_Details', models.CharField(default='', max_length=100)),
                ('Transaction_Description', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='localladder',
            name='shortname',
        ),
        migrations.RemoveField(
            model_name='masterlist',
            name='Transaction_DateTime',
        ),
        migrations.RemoveField(
            model_name='masterlist',
            name='Transaction_Description',
        ),
        migrations.RemoveField(
            model_name='masterlist',
            name='Transaction_Details',
        ),
        migrations.RemoveField(
            model_name='masterlist',
            name='Transaction_Number',
        ),
        migrations.RemoveField(
            model_name='masterlist',
            name='Transaction_Type',
        ),
        migrations.AddField(
            model_name='makecompany',
            name='ActiveOrInactive',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='makeuser',
            name='ActiveOrInactive',
            field=models.CharField(default='', max_length=100),
        ),
    ]
