# Generated by Django 3.1.7 on 2022-02-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0019_auto_20220208_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makecompany',
            name='ActiveOrInactive',
        ),
        migrations.RemoveField(
            model_name='makeuser',
            name='ActiveOrInactive',
        ),
        migrations.AddField(
            model_name='makecompany',
            name='Active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='makeuser',
            name='Active',
            field=models.BooleanField(null=True),
        ),
    ]
