# Generated by Django 3.1.7 on 2022-02-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0020_auto_20220208_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makecompany',
            name='Active',
            field=models.CharField(choices=[('0', 'Female'), ('1', 'male')], default='', max_length=11),
        ),
    ]
