# Generated by Django 3.1.7 on 2022-02-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0021_auto_20220208_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makecompany',
            name='Active',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=1),
        ),
        migrations.AlterField(
            model_name='makeuser',
            name='Active',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=1),
        ),
    ]
